version: '3.8'

services:
  postgres1:
    image: postgres:alpine
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres1:/var/lib/postgresql/data

  postgres2:
    image: postgres:alpine
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres2:/var/lib/postgresql/data
